SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[vw_ASSIGNED_CUSTOMER_AGENTS] AS 

	SELECT	CST.CUST_CODE
		,	CST.CUST_NAME
		,	AGT.AGENT_CODE
		,	AGT.AGENT_NAME
	FROM		dbo.CUSTOMER	CST
	INNER JOIN	dbo.AGENTS	AGT	ON CST.AGENT_CODE = AGT.AGENT_CODE

GO
