CREATE TABLE [dbo].[CUSTOMER]
(
[CUST_CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUST_NAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUST_CITY] [char] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORKING_AREA] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CUST_COUNTRY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GRADE] [int] NULL,
[OPENING_AMT] [decimal] (12, 2) NOT NULL,
[RECEIVE_AMT] [decimal] (12, 2) NOT NULL,
[PAYMENT_AMT] [decimal] (12, 2) NOT NULL,
[OUTSTANDING_AMT] [decimal] (12, 2) NOT NULL,
[PHONE_NO] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AGENT_CODE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExportDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMER] ADD CONSTRAINT [PK__CUSTOMER__8393C4A1D12A6C73] PRIMARY KEY CLUSTERED  ([CUST_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMER] ADD CONSTRAINT [FK__CUSTOMER__AGENT___38996AB5] FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[AGENTS] ([AGENT_CODE])
GO
